config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'

  get '/writing' => 'home#writing'

  post '/send_article_to_db' => 'home#send_article_to_db'

  get '/show', to: 'home#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#writing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.order('id DESC').page params[:page]

  end

  def writing
  end

  def send_article_to_db
    article = Article.new
    article.subject = params[:subject]
    article.content = params[:content]
    article.save

    redirect_to '/'
  end

  def show
    @articles = Article.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p>Let's join the A-Look-So !</p>
<div class="article_list">
  <ul>
    <% @articles.each do |p| %>
      <li>no.<%= p.id %> <%= link_to p.subject, show_path(id: p.id) %></li>
<!--      <li>Content : <%#= p.content %></li>-->
      <br>
    <% end %>
  </ul>
  <%= paginate @articles %>

  <button class="btn btn-primary"> <%= link_to "Write", writing_path%></button>

</div>

app/views/home/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<form action="/show/:id" method="get">
  <div class="article">
    <ul>
      <h1><li>Subject : <%= @articles.subject %></li></h1>
      <li>Content : <%= @articles.content %></li>
      <br>
    </ul>

  </div>
</form>

app/views/home/writing.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<form action="/send_article_to_db" method="post">
  <div class="form-group">
    <label for="inputSubject">Subject</label>
    <input type="text" class="form-control" name="subject" placeholder="Subject">
  </div>

  <div class="form-group">
    <label for="inputContent">Content Area</label>
    <textarea class="form-control" name="content" rows="3" placeholder="Content Area"></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Post It !</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToJoinAlookso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>